version: '2'

services:
  mariadb:
    container_name: bd-microservice
    image: docker.io/bitnami/mariadb:10.6
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_myapp
      - MARIADB_DATABASE=bitnami_myapp
    ports:
      - '3307:3306'
    networks:
      - minha-rede-local
  ms:
    container_name: microservice
    image: docker.io/bitnami/laravel:10
    ports:
      - '8060:8000'
    environment:
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_USERNAME=bn_myapp
      - DB_DATABASE=bitnami_myapp
      - SCOUT_DRIVER=elastic
      - ELASTICSEARCH_HOST=elasticsearch
      - ELASTICSEARCH_PORT=9200
    volumes:
      - './microservice-app:/app'
    depends_on:
      - mariadb
    networks:
      - minha-rede-local
  elasticsearch:
    container_name: elastic-news-api
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.14
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
    networks:
      - minha-rede-local

  rabbitmq:
    container_name: rabbitmq-news-api
    image: 'rabbitmq:3-management'
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      - RABBITMQ_DEFAULT_USER=newsapi
      - RABBITMQ_DEFAULT_PASS=newsapi
    networks:
      - minha-rede-local

networks:
  minha-rede-local:
    external: true